plugins {
    id 'com.android.application'
}

android {
    namespace 'com.karaokeflow.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.karaokeflow.app'
        minSdk 26
        targetSdk 28
        versionCode 6
        versionName '0.5.1-sf2'

        externalNativeBuild {
            cmake {
                cppFlags '-std=c++11'
            }
        }

        ndk {
            abiFilters 'arm64-v8a', 'armeabi-v7a'
        }
    }

    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
            version '3.22.1'
        }
    }
}
